CMakeLists.txt
SYCLStream.cpp
cmake/Modules/FindComputeCpp.cmake

This patch updates the CMake building options to support the [Codelay ComputeCpp Community Edition 0.1](https://www.codeplay.com/products/computesuite/computecpp), including the FindComputeCpp CMake module provided with the [ComputeCpp SDK](https://github.com/codeplaysoftware/computecpp-sdk).
The patch also includes minor performance tuning changes for SYCL. First, we pre-compile the kernel binaries in the setting up, like the OCLStream variant. By default on SYCL, the OpenCL program is compiled on demand in the Parallel For. 
The accessors syntax is also changed to use linear access, which simplifies the work of the device compiler.
In order to build with ComputeCpp, only the standard CMake flags from the SDK are required:
` cmake ../
-DHAS_SYCL=ON \ …

Updated the SYCL Stream benchmark with latest ComputeCpp CE 0.1.1 Edition

---

SYCL.make
SYCLStream.cpp

This pull request contains:
-  An update to SYCL.make to use a new variable, containing the path to the ComputeCpp installation. The variable is `COMPUTECPP_PACKAGE_ROOT_DIR`, matching the one used in the build for [ComputeCpp SDK](https://github.com/codeplaysoftware/computecpp-sdk).

Updated the Makefile for SYCL 

---

SYCLStream.cpp

* Retrieving a host accessor does not require a target anymore

Update benchmark to work with ComputeCpp CE 0.6.1

---

OCLStream.cpp
SYCL.make
SYCLStream.cpp

* Fix for OpenCL/SYCL behaviour with global objects
* Separated makefile for SYCL to get more concise error messages and reduce compilation time

Minor SYCL and OpenCL fixes

---

CHANGELOG.md
main.cpp

This sets MiB = 2^20, GiB = 2^30 rather than the default of
MB = 10^6 and GB = 10^9.
This would fix #55 .

Add a --mibibytes flag to output bandwidth and array sizes in base 2

---

SYCLStream.cpp
SYCLStream.h

**1. Deprecated code**
```
'get_global' is deprecated: SYCL 1.2.1
revision 3 replaces nd_item::get_global with nd_item::get_global_id.
```
```
'get_local' is deprecated: SYCL 1.2.1 revision 3 replaces
nd_item::get_local with nd_item::get_local_id.
```
**2. Non-official code**
Before closing this with saying "ComputeCpp claims it fully conformant with SYCL 1.2.1", please note that while this is correct, the notion of using the pre-built kernel in with `parallel_for` is _not currently_ part of the SYCL Specification - v1.2.1 Revision 5.
**The issue:**
The SYCL specification does not include an overload of `handler::parallel_for` that accepts syclKernel built from a program. For example, `parallel_for(syclKernel, nd_range, functor)` is not conformant with specification at the moment. The …

Making BabelStream's SYCL code compliant

---

ACCStream.cpp
CHANGELOG.md
OpenACC.make

This adds GNU OpenACC support, similar to that recently added for OpenMP. There's also a few code changes needed to support GNU C++ and AMD devices.
* Autodetect the device type, rather than hard-code NVidia.
* Add GNU command line options to the makefile, and adjust the "restrict"
extension usage. For now, we assume the toolchain is only configured for one
accelerator.

Add GNU OpenACC support for AMD GCN

---

.gitignore
Kokkos.make
README.md

In light of https://github.com/kokkos/kokkos/issues/3178, this PR adds support for the new Kokkos 3+ style Makefile where Kokkos is compiled together with the client code.
This breaks compatibility with Kokkos 2.x.

Update Kokkos to support version 3+

---

Kokkos.make
OpenMP.make

Includes a minor bug fix for GCC where the `-fopenmp`  flag was not included.

Added support for Cray, PGI, and Armclang for Kokkos and OpenMP

---

OpenMP.make

GCC on PPC requires weird flags

Add PPC+GNU combination

---

OCLStream.h

This patch changes the OpenCL resource destructor call order.
This was the observed behavior before the patch:
```
22:43:37.600794636 - lttng_ust_opencl:clReleaseContext_entry: context: 0xa193b0
22:43:37.600795360 - lttng_ust_opencl:clReleaseContext_exit: errcode_ret_val: CL_SUCCESS
22:43:37.600795553 - lttng_ust_opencl:clReleaseDevice_entry: device: 0x915b20
22:43:37.600795746 - lttng_ust_opencl:clReleaseDevice_exit: errcode_ret_val: CL_SUCCESS
22:43:37.600796192 - lttng_ust_opencl:clReleaseMemObject_entry: memobj: 0xa110d0
22:43:37.600811810 - lttng_ust_opencl:clReleaseMemObject_exit: errcode_ret_val: CL_SUCCESS
22:43:37.600812203 - lttng_ust_opencl:clReleaseMemObject_entry: memobj: 0x9dfe20
22:43:37.603779984 - lttng_ust_opencl:clReleaseMemObject_exit: errcode_ret_val: CL_SUCCESS …
```

Ensure OpenCL destructors are called in the "correct" order.

---

.gitignore
CHANGELOG.md
README.md
STD.make
STDStream.cpp
STDStream.h
main.cpp

This commits adds an implementation using the C++ parallel STL.
The Makefile uses the NVIDIA HPC SDK `nvc++` compiler with the `-stdpar` flag.
Tested using the NVIDIA HPC SDK 20.9.

Add NVIDIA HPC SDK C++ parallel STL implementation

---

SYCL.make

So it turns out there was an oversight for ComputeCpp in https://github.com/UoB-HPC/BabelStream/commit/f0403d2b092115a6b0146cd030ff4a006520d3a9 where the sycl kernel isn't actually included in the compiled binary.
The effect of this is quite surprising: when ran on the host device, everything works, but if we choose any other SYCL device, it throws a `sycl::invalid_object_error` exception on the first submit call.
I suspect the original commit was accidentally tested with the host device.
ComputeCpp's official Makefile template now uses the `compute++` compiler to compile everything so we also default to that.
I've looked into whether we can reuse the original dependency chain but I gave up and made it conditional instead;
dissecting their CMake plugin, it shows further *.bc and *.sycl …

Fixed sycl kernel linking for computecpp

---

ACCStream.cpp
ACCStream.h
CHANGELOG.md
CUDAStream.cu
CUDAStream.h
HIPStream.cpp
HIPStream.h
KokkosStream.cpp
KokkosStream.hpp
OCLStream.cpp
OCLStream.h
OMPStream.cpp
OMPStream.h
README.md
STD20Stream.cpp
STD20Stream.hpp
STDStream.cpp
STDStream.h
SYCLStream.cpp
SYCLStream.h
Stream.h
main.cpp

This PR adds a new kernel to BabelStream, the `nstream` kernel borrowed from [PRK](https://github.com/ParRes/Kernels).
The new kernel computes:
```
a[i] += b[i] + scalar * c[i];
```
This has 3 reads and 1 write which is a heaver read ratio than Triad. Non-temporal stores on CPUs are also not required as the `a` array must be first read and be placed in cache.
~To support this, the initial values of the arrays are changed to ensure the results validate.~ no longer required.
The OpenACC kernel does not seem to respect the `+=`; it does not include the initial value of `a` just overwrites it the same as Triad which is incorrect.
The modern C++ is hard to test because not all compilers support the required APIs in the Parallel STL, or else the software stack is fragile.

Add PRK Nstream kernel

---

OMPStream.cpp
RAJAStream.cpp

Silence "error: there are no arguments to 'aligned_alloc' that depend
on a template parameter, so a declaration of 'aligned_alloc' must be
available"
* OMPStream.cpp: #include <stdlib.h>.
* RAJAStream.cpp: Likewise.

Include stdlib.h for aligned_alloc

---

.gitignore
CMakeLists.txt
README.md
TBB.cmake
TBB.make
TBBStream.cpp
TBBStream.hpp
ci-prepare-bionic.sh
ci-test-compile.sh
main.cpp

This PR adds the TBB (or oneTBB) implementation, thus closing #74.
The implementation is fairly straightforward as TBB exposes a very similar API to SYCL but without device/host memory distinctions.
We expose the *partitioner* parameter, common to most parallel algorithms, as the device option:
```shell
> tbb-stream --list
[0] auto partitioner
[1] affinity partitioner
[2] static partitioner
[3] simple partitioner
See https://spec.oneapi.com/versions/latest/elements/oneTBB/source/algorithms.html#partitioners for more details
```
Partitioners isn't an abstract class so TBB implements it as overloads for each exported `parallel_*` function.
To allow selecting partitioners as a runtime option, C++14 auto lambda parameters with forwarding was used to specialise for each case with minimal (very …

Initial TBB implementation

---

.github/workflows/main.yaml
JuliaStream.jl/.JuliaFormatter.toml
JuliaStream.jl/.gitignore
JuliaStream.jl/AMDGPU/Manifest.toml
JuliaStream.jl/AMDGPU/Project.toml
JuliaStream.jl/CUDA/Manifest.toml
JuliaStream.jl/CUDA/Project.toml
JuliaStream.jl/KernelAbstractions/Manifest.toml
JuliaStream.jl/KernelAbstractions/Project.toml
JuliaStream.jl/Manifest.toml
JuliaStream.jl/Project.toml
JuliaStream.jl/README.md
JuliaStream.jl/Threaded/Manifest.toml
JuliaStream.jl/Threaded/Project.toml
JuliaStream.jl/oneAPI/Manifest.toml
JuliaStream.jl/oneAPI/Project.toml
JuliaStream.jl/src/AMDGPUStream.jl
JuliaStream.jl/src/CUDAStream.jl
JuliaStream.jl/src/DistributedStream.jl
JuliaStream.jl/src/JuliaStream.jl
JuliaStream.jl/src/KernelAbstractionsStream.jl
JuliaStream.jl/src/PlainStream.jl
JuliaStream.jl/src/Stream.jl
JuliaStream.jl/src/StreamData.jl
JuliaStream.jl/src/ThreadedStream.jl
JuliaStream.jl/src/oneAPIStream.jl
JuliaStream.jl/update_all.sh

This PR adds the Julia implementation of BabelStream with the following implementations:
* `PlainStream.jl` - Single threaded `for`
* `ThreadedStream.jl` - Threaded implementation with `Threads.@threads` macros
* `DistributedStream.jl` - Process based parallelism with `@distributed` macros
* `CUDAStream.jl` - Direct port of BabelStream's native CUDA implementation using [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl)
* `AMDGPUStream.jl` - Direct port of BabelStream's native HIP implementation using [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl)
See README.md for details on build and run instructions.
Performance is surprisingly good across all supported hardware platforms.
All benchmarks uses Julia 1.6.1, specific versions of each package are available in `Manifest.toml`
AMDGPU.jl is …

Julia implementation

---

README.md

I noticed the README was out of date with the current model options available by BabelStream. I did not implement any further changes.

Reflect updated model options in README

---

CMakeLists.txt

Hi, I noticed `RELEASE_FLAGS` and `DEBUG_FLAGS` are not respected. Here is a quick fix.

Fix a bug in the CMake script where override flags are ignored

---

src/thrust/ThrustStream.cu

fixes https://github.com/UoB-HPC/BabelStream/issues/142 except for the CMake part, which i attempted in vain to address.
Signed-off-by: Jeff Hammond <jehammond@nvidia.com>

accept NVHPC NVC++ as a CUDA compiler when it is so

---

.gitignore
src/.gitignore
src/fortran/ArrayStream.F90
src/fortran/BabelStreamTypes.F90
src/fortran/CUDAKernelStream.F90
src/fortran/CUDAStream.F90
src/fortran/DoConcurrentStream.F90
src/fortran/Makefile
src/fortran/OpenACCArrayStream.F90
src/fortran/OpenACCStream.F90
src/fortran/OpenMPStream.F90
src/fortran/OpenMPTargetLoopStream.F90
src/fortran/OpenMPTargetStream.F90
src/fortran/OpenMPTaskloopStream.F90
src/fortran/OpenMPWorkshareStream.F90
src/fortran/SequentialStream.F90
src/fortran/build.sh
src/fortran/main.F90
src/fortran/make.inc.amd
src/fortran/make.inc.arm
src/fortran/make.inc.cray
src/fortran/make.inc.fj
src/fortran/make.inc.gcc
src/fortran/make.inc.nvhpc
src/fortran/make.inc.oneapi
src/fortran/run.sh
src/thrust/ThrustStream.cu

This is a new implementation of BabelStream using Fortran.
The code uses a Fortran driver that is largely equivalent to the C++ one, with a few exceptions.  First, it does not use a C++ class for the `stream` object, since that doesn't seem like a useful way to do things in Fortran.  Instead, I use a module that contains the same methods, and which has `alloc` and `dealloc` that act like CTOR and DTOR.
The current implementations are:
* `DO CONCURRENT`
* Fortran array notation
* Sequential `DO` loops
* OpenACC `parallel loop`
* OpenACC `kernels` on Fortran array notation
* OpenMP `parallel do`
* OpenMP `taskloop`
* OpenMP `target teams distribute parallel do simd`
* OpenMP `target teams loop`
* CUDA Fortran (handwritten CUDA Fortran kernels, except DOT)
* CUDA Fortran kernels (`!$cuf …

Fortran ports

---

src/sycl2020/model.cmake

Added ICPX support for the OneAPI 2023 and later versions since DPCPP is deprecated

Added ICPX support for the OneAPI 2023 support

---

src/hip/HIPStream.cpp
src/hip/HIPStream.h
src/hip/model.cmake

PR Summary:
- The number of blocks launched for the dot kernel has been modified.
- The partial sums for the dot-kernel is allocated using `hipHostMalloc`, which allocates in a device-visible page. Memory transfer occurs asynchronously and, as a result, requires a `hipDeviceSynchronize` after the kernel is called.
- A number of other minor kernel updates using recommended syntax.
Happy to discuss how much of this you want upstream. For reference (before/after) numbers, here are some quick results in double precision:
**Reference (baseline - develop)**: Ran on an MI-210 with the following arguments with an array size of 2^28 elements: `-s $((2**28))`
```
Function    MBytes/sec  Min (sec)   Max         Average     
Copy        1406620.269 0.00305     0.00322     0.00308     
Mul …
```

Updated hip kernels

---

src/raja/model.cmake

Project now compiles with both v0.14.1 and v2022.10.5, tested with OpenMP and CUDA.
This addresses #114 .

Fix RAJA > v0.14.1 compatibility

---

README.md

The sycl2020 model variant name needs an update to comply with naming scheme in Babelstream 5.0

Update README.md to Address Changes in SYCL2020 Renaming

---

src/dpl_shim.h

Reverts UoB-HPC/BabelStream#177

Revert "Remove AdaptiveCpp workaround in dpl_shim.h to allow for automatic prefetch optimization"
